# Create a new user
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user3@notfound.local",
  "dateBirth": "2004-09-21",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456",
  "city": "Москва",
  "role": "Заказчик",
  "specialization": ["электрик", "электрик", "электрик", "электрик", "agwgw"],
  "personalInfo": "Женат"
}

###

# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "1234567"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGUzZDI5YzkwNTlkNjAyYmNhNTY3NmIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29udHJhY3RvciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzMiIsInRva2VuSWQiOiJlZTczNzA4ZS1hYTkxLTQ5MGUtODU2ZS1kMjM3ZTAwZTliNDAiLCJpYXQiOjE2OTI5NjgyOTUsImV4cCI6MTY5NTU2MDI5NX0.XcfTqa2ykUjEBEN1XpQ9-xdT_t-dkjihTD0mhOvcUhk


###

# Update user
PATCH http://localhost:4000/api/users/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjkzMTY0ODQ4LCJleHAiOjE2OTMxNjU0NDh9.9L8M2s9RA9hdvrLJjV7QU4mxxvFJc-B0Ayow4YdKipQ

{
  "firstname": "Keks7",
  "lastname": "Smith2"
}

###

# Change user password
PATCH http://localhost:4000/api/users/changePassword HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTFlOWU2YThhYjQwOTMzMTBjZDciLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItCY0YHQv9C-0LvQvdC40YLQtdC70YwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzEyOTUzNSwiZXhwIjoxNjkzMTMwMTM1fQ.D0kmFybm1P3amdPp8uQmlEwEw2ZaeK8c5C006R27oKU

{
  "password": "1234567",
  "newPassword": "12345"
}

###

###################################################

# Create a new task
POST http://localhost:4000/api/task HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgyIiwiZmlyc3RuYW1lIjoiS2VrczciLCJpYXQiOjE2OTMxNjkzMTYsImV4cCI6MTY5MzE2OTkxNn0.n47NlD4dqoqoB9oAhs3HfCSeNQHcpI7vRGFaYoffYpA

{
  "title": "Решить задач1dbea456gegbebee78910",
  "description": "Решить задачу по математике Решить задачу по математике Решить задачу по математике Решить задачу по математике",
  "cityId": 1,
  "categories": [1],
  "tags": [1],
  "price": 250,
  "address": "1233451234567",
  "dedline": "2023-08-29"
}

###

# Update Task by id
PATCH http://localhost:4000/api/task/15 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgyIiwiZmlyc3RuYW1lIjoiS2VrczciLCJpYXQiOjE2OTMxNjkzMTYsImV4cCI6MTY5MzE2OTkxNn0.n47NlD4dqoqoB9oAhs3HfCSeNQHcpI7vRGFaYoffYpA

###

####################################################

# Create a new comment
POST http://localhost:4000/api/task/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgyIiwiZmlyc3RuYW1lIjoiS2VrczciLCJpYXQiOjE2OTMxNjkzMTYsImV4cCI6MTY5MzE2OTkxNn0.n47NlD4dqoqoB9oAhs3HfCSeNQHcpI7vRGFaYoffYpA

{
  "message": "Проверка 3 комментариев user",
  "taskId": 17
}

###

# Get all comments and filtres
GET http://localhost:4000/api/task/comments?limit=10&page=1 HTTP/1.1

###

# Delete comment by id
DELETE http://localhost:4000/api/task/comments/17 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjkzMTU0MTQ1LCJleHAiOjE2OTMxNTQ3NDV9.cxinG6Wt0xOnST6398Ky3l5FmAxkyVij28QhwP8sH6I

###
