# Create a new user
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user4@notfound.local",
  "dateBirth": "1988-03-12",
  "firstname": "Keks4",
  "lastname": "Smith4",
  "password": "123456",
  "city": "Санкт-Петербург",
  "role": "Заказчик"
}

###

# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzODUwNjFlNDU4Y2NkMGExZmY2MTkiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwidG9rZW5JZCI6ImYxNjI4MGY4LTEwOTItNDdhMC05NWNjLWFlYTA1NzJjZDY0ZSIsImlhdCI6MTY5MzY4MTEyMSwiZXhwIjoxNjk2MjczMTIxfQ.HTwNsCK9rgAg1UpSqrT2D3PYzRDZkXKUKM3Ski7yPdI

###

# Upload avatar for user by id
POST http://localhost:4000/api/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzODUwNjFlNDU4Y2NkMGExZmY2MTkiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGg1IiwiZmlyc3RuYW1lIjoiS2VrczQiLCJpYXQiOjE2OTM3MzkxMjcsImV4cCI6MTY5MzczOTcyN30.qRIBdoPT-cAexEY3Nz6K-nuNsBQ6erQc85I7DCv0Kbg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="Визуализация.png"

< C:\Users\gerbe\Pictures\Визуализация.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Update user
PATCH http://localhost:4000/api/users/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzODUwNjFlNDU4Y2NkMGExZmY2MTkiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGg1IiwiZmlyc3RuYW1lIjoiS2VrczQiLCJpYXQiOjE2OTM2ODkxNzksImV4cCI6MTY5MzY4OTc3OX0.SX1TVOnVNUKGflvWBt8oDKBXEfE6Eoi65pkS5h-_u8w

{
  "specialization": ["Электрик"]
}

###

# Change user password
PATCH http://localhost:4000/api/users/changePassword HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzODUwNjFlNDU4Y2NkMGExZmY2MTkiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGg1IiwiZmlyc3RuYW1lIjoiS2VrczQiLCJpYXQiOjE2OTM2ODkzMTYsImV4cCI6MTY5MzY4OTkxNn0.K-8vycz8R0xx0rA2jmCr7DoiAWgqKR3GKqnRw04fNiw

{
  "password": "123456",
  "newPassword": "123456"
}

###

# Get user by id
GET http://localhost:4000/api/users/64f471ff9d4542f4028081fd HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzODUwNjFlNDU4Y2NkMGExZmY2MTkiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGg1IiwiZmlyc3RuYW1lIjoiS2VrczQiLCJpYXQiOjE2OTM3NDEzOTEsImV4cCI6MTY5Mzc0MTk5MX0.EWlIT7wtLrg4gN5moufh6c8Mbznv32z_Z9yztM-9qVI

###



###################################################

# Create a new task
POST http://localhost:4000/api/task HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgyIiwiZmlyc3RuYW1lIjoiS2VrczciLCJpYXQiOjE2OTMyMzI2MTYsImV4cCI6MTY5MzIzMzIxNn0.qAFfV7cIl9Cji_U7X8nf4Qv9eIel0C4JMN1kpz0wy4s

{
  "title": "Решить задач1dbea456gegbebee78910",
  "description": "Решить задачу по математике Решить задачу по математике Решить задачу по математике Решить задачу по математике",
  "cityId": 1,
  "categories": [1],
  "tags": [1],
  "price": 250,
  "address": "1233451234567",
  "dedline": "2023-08-29"
}

###

# Add response on Task by id
PATCH http://localhost:4000/api/task/response/17 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTFlOWU2YThhYjQwOTMzMTBjZDciLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItCY0YHQv9C-0LvQvdC40YLQtdC70YwiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzI5MTIyNSwiZXhwIjoxNjkzMjkxODI1fQ.1PPibJPnQrtaRtX8n_ux0V8PEb9yZnstsC4S20wvu9E

###

# Change status of Task by id
PATCH http://localhost:4000/api/task/status/54?status=Провалено HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYwNzg4YzgzN2U5MWNlOTMxYTMxMGIiLCJlbWFpbCI6InVzZXI4OUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQmNGB0L_QvtC70L3QuNGC0LXQu9GMIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2OTM0ODExMDUsImV4cCI6MTY5MzQ4MTcwNX0.Ezo7an961N1SkrHZfB1fVBpixMx7KZX24nw0FIAUbyE

###

# Delete Task by id
DELETE http://localhost:4000/api/task/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgyIiwiZmlyc3RuYW1lIjoiS2VrczciLCJpYXQiOjE2OTMzMjMzNDEsImV4cCI6MTY5MzMyMzk0MX0.0BAUtLEEvze2iZILzG11GoqQPD9O4V1AU3ymuVdtSFo

###

####################################################






# Create a new comment
POST http://localhost:4000/api/task/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgyIiwiZmlyc3RuYW1lIjoiS2VrczciLCJpYXQiOjE2OTMyMzI2MTYsImV4cCI6MTY5MzIzMzIxNn0.qAFfV7cIl9Cji_U7X8nf4Qv9eIel0C4JMN1kpz0wy4s

{
  "message": "Проверка 3 комментариев user",
  "taskId": 17
}

###

# Get all comments and filtres
GET http://localhost:4000/api/task/comments?limit=10&page=1 HTTP/1.1

###

# Delete comment by id
DELETE http://localhost:4000/api/task/comments/17 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YTIwZGU2YThhYjQwOTMzMTBjZGIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0JfQsNC60LDQt9GH0LjQuiIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjkzMTU0MTQ1LCJleHAiOjE2OTMxNTQ3NDV9.cxinG6Wt0xOnST6398Ky3l5FmAxkyVij28QhwP8sH6I

###
