# Create a new review
POST http://localhost:3333/api/review/ HTTP/1.1
Content-Type: application/json

{
  "taskId": 15,
  "userId": "64e9a1e9e6a8ab4093310cd7",
  "rating": 3,
  "message": "Проверка 2 работы отзывов Проверка работы отзывов Проверка работы отзывов Проверка работы отзывов"
}

###
